
$ModelName "props_combine\suit_charger001.mdl"

$BodyGroup "Body"
{
	studio "suit_charger001_reference.smd"
}

$Include "suit_charger001_lod.qci"

$SurfaceProp "metal"

$Contents "solid"

$IllumPosition -0.008 -3.995 0.002

$CDMaterials "models\props_combine\"

// $Include "suit_charger001_box.qci"

$Include "suit_charger001_bone.qci"

$Include "suit_charger001_animation.qci"

$Include "suit_charger001_collision.qci"
